sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Gintama3ren
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBsvcN9NrGZ4GhrsLbT
    access-key-secret: SNS9uBJYwGkZEtaocP9WGRDXmclv8x
    bucket-name: ll-skybucket
  redis:
    host: localhost
    port: 6379

